server:
  port: 8080

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/todolist?currentSchema=todoApp"
    username: "postgres"
    password: "1234567"
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      continue-on-error: false

springdoc:
  override-with-generic-response: false